build:
        environment:
                php:
                        version: 7.4.6
                        pecl_extensions:
                                - phalcon
                                - zip
        nodes:
                analysis:
                        dependencies:
                                after:
                                        - composer require --dev phalcon/ide-stubs
                                        - composer require --dev mikopbx/core
                        project_setup:
                                override:
                                        - 'true'
                        tests:
                                override:
                                        - php-scrutinizer-run
                                        -
                                                command: phpcs-run
                                                use_website_config: true
                                        - js-scrutinizer-run
                tests: true
        tests:
                override:
                        command: "php -v"
checks:
        php:
                fix_php_opening_tag: false
                remove_php_closing_tag: true
                one_class_per_file: true
                side_effects_or_types: false
                no_mixed_inline_html: false
                require_braces_around_control_structures: true
                php5_style_constructor: false
                no_global_keyword: true
                avoid_usage_of_logical_operators: false
                psr2_class_declaration: true
                no_underscore_prefix_in_properties: true
                no_underscore_prefix_in_methods: true
                blank_line_after_namespace_declaration: false
                single_namespace_per_use: false
                psr2_switch_declaration: true
                psr2_control_structure_declaration: true
                avoid_superglobals: true
                security_vulnerabilities: true
                no_exit: false
        javascript:
                var_sometimes_initialized: true
                var_never_initialized: true
                valid_typeof: true
                use_isnan: true
                unsafe_undefined: true
                unsafe_mutable_variable_usage: true
                nsp_vulnerabilities: true
                no_with: true
                no_void: true
                no_use_before_define: true
                no_unused_vars: true
                no_unused_function: true
                no_unused_expressions: true
                no_unused_const: true
                no_unused_assignment: true
                no_unreachable: true
                no_undef_init: true
                no_undef: true
                no_sparse_arrays: true
                no_shadow_builtins: true
                no_sequences: true
                no_return_assign: true
                no_redeclared_const: true
                no_redeclare: true
                no_process_exit: true
                no_path_concat: true
                no_new_wrappers: true
                no_new_require: true
                no_new_func: true
                no_negated_in_lhs: true
                no_native_reassign: true
                no_label_var: true
                no_invalid_regexp: true
                no_inner_declarations: true
                no_implied_eval: true
                no_func_assign: true
                no_extra_bind: true
                no_extend_native: true
                no_ex_assign: true
                no_eval: true
                no_empty_label: true
                no_empty_class: true
                no_empty: true
                no_dupe_keys: true
                no_delete_var: true
                no_debugger: true
                no_constant_condition: true
                no_console: true
                no_comma_dangle: true
                no_caller: true
                no_bitwise: true
                no_array_constructor: true
                no_alias_builtins: true
                new_cap: true
                jsdoc_non_existent_params: true
                jsdoc_no_duplicate_params: true
                guard_for_in: true
                duplicate_code: true
                curly: true
                consistent_return: true
                code_rating: true
                check_unused_parameters: true
                check_unused_object_creation: true
                check_unused_member_calls: true
                check_unnecessary_return: true
                check_unnecessary_continue: true
                check_undeclared_vars: true
                check_try_statement: true
                check_too_many_arguments: true
                'check_switch_unintended label': true
                'check_switch_no_uncommented_fallthrough"': true
                check_switch_no_default: true
                check_switch_default_only: true
                check_switch_default_not_last: true
                check_switch_ambiguous_test: true
                check_loop_no_body: true
                check_for_loops_test: true
coding_style:
        php:
                indentation:
                        general:
                                use_tabs: false
                                size: 4
                        switch:
                                indent_case: true
                spaces:
                        general:
                                linefeed_character: newline
                        before_parentheses:
                                function_declaration: false
                                closure_definition: false
                                function_call: false
                                if: true
                                for: true
                                while: true
                                switch: true
                                catch: true
                                array_initializer: false
                        around_operators:
                                assignment: true
                                logical: true
                                equality: true
                                relational: true
                                bitwise: true
                                additive: true
                                multiplicative: true
                                shift: true
                                unary_additive: false
                                concatenation: false
                                negation: false
                        before_left_brace:
                                class: true
                                function: true
                                if: true
                                else: true
                                for: true
                                while: true
                                do: true
                                switch: true
                                try: true
                                catch: true
                                finally: true
                        before_keywords:
                                else: true
                                while: true
                                catch: true
                                finally: true
                        within:
                                brackets: false
                                array_initializer: false
                                grouping: false
                                function_call: false
                                function_declaration: false
                                if: false
                                for: false
                                while: false
                                switch: false
                                catch: false
                                type_cast: false
                        ternary_operator:
                                before_condition: true
                                after_condition: true
                                before_alternative: true
                                after_alternative: true
                                in_short_version: false
                        other:
                                before_comma: false
                                after_comma: true
                                before_semicolon: false
                                after_semicolon: true
                                after_type_cast: true
                braces:
                        classes_functions:
                                class: new-line
                                function: new-line
                                closure: new-line
                        if:
                                opening: undefined
                                always: true
                                else_on_new_line: false
                        for:
                                opening: undefined
                                always: true
                        while:
                                opening: undefined
                                always: true
                        do_while:
                                opening: undefined
                                always: true
                                while_on_new_line: false
                        switch:
                                opening: undefined
                        try:
                                opening: undefined
                                catch_on_new_line: false
                                finally_on_new_line: false
                upper_lower_casing:
                        keywords:
                                general: lower
                        constants:
                                true_false_null: lower

filter:
        excluded_paths:
                - "*.min.js"
        dependency_paths:
                - vendor/